### ISSUE TITLE
User with full shell access can't send data to SFTP

### ISSUE THREAD

**Issue by prakharagarwal** [embulk/embulk-output-sftp#15]
Embulk is able to send data to SFTP if the user has restricted privileges (no shell access) to upload data.

When we specify a regular SFTP user who has full shell access, authentication is working but data push is not happening and it is simply hanging. Could you please let us know whether this is an expected behavior or do we need make any configuration changes to support regular SFTP user?

**Comment by sakama** [comment]
Hi.

Could this user get files with sftp command or GUI SFTP client?
If yes, I think something fixes are required for embulk-output-sftp.

If no, configuration changes of server should be required.
* permissions(confirm parent directory or file is writeable)
* chroot settings change if using

and showing us a stacktrace is helpfull to solve this problem.
Thanks.

**Comment by sakama** [comment]
@civitaspo He is my colleagues and I think it's ok to close this issue.
I don't have permission to close this one.

Thanks.
